/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeemanagementsystem;

/**
 *
 * @author INN
 */
public class WelcomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginInterface
     */
    Admin admin;
    public WelcomeScreen() {
         admin = new Admin(0,null, null, null, 0, null, null, 0, 0, null, null, 0, null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelSide = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        viewAttB1 = new javax.swing.JButton();
        delAttB = new javax.swing.JButton();
        addBonusButton = new javax.swing.JButton();
        viewBonusButton = new javax.swing.JButton();
        updateBonusButton = new javax.swing.JButton();
        deleteBonusButton = new javax.swing.JButton();
        assignBonusButton = new javax.swing.JButton();
        editAttB = new javax.swing.JButton();
        generateSalary = new javax.swing.JButton();
        viewGeneratedSalary = new javax.swing.JButton();
        AddEmployeeB = new javax.swing.JButton();
        ViewEmployeeB = new javax.swing.JButton();
        UpdateEmployeeB = new javax.swing.JButton();
        DeleteEmployeeB = new javax.swing.JButton();
        viewGeneratedSalary1 = new javax.swing.JButton();
        viewAttB2 = new javax.swing.JButton();
        viewAttB3 = new javax.swing.JButton();
        viewAttB4 = new javax.swing.JButton();
        viewAttB5 = new javax.swing.JButton();
        viewAttB6 = new javax.swing.JButton();
        viewGeneratedSalary2 = new javax.swing.JButton();
        viewAttB7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBorder(new javax.swing.border.MatteBorder(null));
        MainPanel.setForeground(new java.awt.Color(51, 51, 255));
        MainPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 51, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText(" WELCOME TO EMPLOYEE MANAGEMENT SYSTEM");

        PanelSide.setBackground(new java.awt.Color(51, 51, 255));
        PanelSide.setPreferredSize(new java.awt.Dimension(130, 600));
        PanelSide.setRequestFocusEnabled(false);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeemanagementsystem/icon (3).jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Admin Portal");

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSideLayout = new javax.swing.GroupLayout(PanelSide);
        PanelSide.setLayout(PanelSideLayout);
        PanelSideLayout.setHorizontalGroup(
            PanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelSideLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelSideLayout.setVerticalGroup(
            PanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        viewAttB1.setBackground(new java.awt.Color(51, 51, 255));
        viewAttB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewAttB1.setForeground(new java.awt.Color(255, 255, 204));
        viewAttB1.setText("View Attendance");
        viewAttB1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAttB1.setMaximumSize(new java.awt.Dimension(150, 50));
        viewAttB1.setMinimumSize(new java.awt.Dimension(150, 50));
        viewAttB1.setPreferredSize(new java.awt.Dimension(150, 50));
        viewAttB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAttB1ActionPerformed(evt);
            }
        });

        delAttB.setBackground(new java.awt.Color(51, 51, 255));
        delAttB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delAttB.setForeground(new java.awt.Color(255, 255, 204));
        delAttB.setText("Delete Attendance");
        delAttB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delAttB.setMaximumSize(new java.awt.Dimension(150, 50));
        delAttB.setMinimumSize(new java.awt.Dimension(150, 50));
        delAttB.setPreferredSize(new java.awt.Dimension(150, 50));
        delAttB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAttBActionPerformed(evt);
            }
        });

        addBonusButton.setBackground(new java.awt.Color(51, 51, 255));
        addBonusButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBonusButton.setForeground(new java.awt.Color(255, 255, 204));
        addBonusButton.setText("Add Bonus");
        addBonusButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBonusButton.setMaximumSize(new java.awt.Dimension(150, 50));
        addBonusButton.setMinimumSize(new java.awt.Dimension(150, 50));
        addBonusButton.setPreferredSize(new java.awt.Dimension(150, 50));
        addBonusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBonusButtonActionPerformed(evt);
            }
        });

        viewBonusButton.setBackground(new java.awt.Color(51, 51, 255));
        viewBonusButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewBonusButton.setForeground(new java.awt.Color(255, 255, 204));
        viewBonusButton.setText("View Bonus");
        viewBonusButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewBonusButton.setMaximumSize(new java.awt.Dimension(150, 50));
        viewBonusButton.setMinimumSize(new java.awt.Dimension(150, 50));
        viewBonusButton.setPreferredSize(new java.awt.Dimension(150, 50));
        viewBonusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBonusButtonActionPerformed(evt);
            }
        });

        updateBonusButton.setBackground(new java.awt.Color(51, 51, 255));
        updateBonusButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBonusButton.setForeground(new java.awt.Color(255, 255, 204));
        updateBonusButton.setText("Update Bonus");
        updateBonusButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateBonusButton.setMaximumSize(new java.awt.Dimension(150, 50));
        updateBonusButton.setMinimumSize(new java.awt.Dimension(150, 50));
        updateBonusButton.setPreferredSize(new java.awt.Dimension(150, 50));
        updateBonusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBonusButtonActionPerformed(evt);
            }
        });

        deleteBonusButton.setBackground(new java.awt.Color(51, 51, 255));
        deleteBonusButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBonusButton.setForeground(new java.awt.Color(255, 255, 204));
        deleteBonusButton.setText("Delete Bonus");
        deleteBonusButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBonusButton.setMaximumSize(new java.awt.Dimension(150, 50));
        deleteBonusButton.setMinimumSize(new java.awt.Dimension(150, 50));
        deleteBonusButton.setPreferredSize(new java.awt.Dimension(150, 50));
        deleteBonusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBonusButtonActionPerformed(evt);
            }
        });

        assignBonusButton.setBackground(new java.awt.Color(51, 51, 255));
        assignBonusButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        assignBonusButton.setForeground(new java.awt.Color(255, 255, 204));
        assignBonusButton.setText("Assign Bonus");
        assignBonusButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        assignBonusButton.setMaximumSize(new java.awt.Dimension(150, 50));
        assignBonusButton.setMinimumSize(new java.awt.Dimension(150, 50));
        assignBonusButton.setPreferredSize(new java.awt.Dimension(150, 50));
        assignBonusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBonusButtonActionPerformed(evt);
            }
        });

        editAttB.setBackground(new java.awt.Color(51, 51, 255));
        editAttB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editAttB.setForeground(new java.awt.Color(255, 255, 204));
        editAttB.setText("Edit Attendance");
        editAttB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editAttB.setMaximumSize(new java.awt.Dimension(150, 50));
        editAttB.setMinimumSize(new java.awt.Dimension(150, 50));
        editAttB.setPreferredSize(new java.awt.Dimension(150, 50));
        editAttB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAttBActionPerformed(evt);
            }
        });

        generateSalary.setBackground(new java.awt.Color(51, 51, 255));
        generateSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        generateSalary.setForeground(new java.awt.Color(255, 255, 204));
        generateSalary.setText("Generate Salary");
        generateSalary.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generateSalary.setMaximumSize(new java.awt.Dimension(150, 50));
        generateSalary.setMinimumSize(new java.awt.Dimension(150, 50));
        generateSalary.setPreferredSize(new java.awt.Dimension(150, 50));
        generateSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateSalaryActionPerformed(evt);
            }
        });

        viewGeneratedSalary.setBackground(new java.awt.Color(51, 51, 255));
        viewGeneratedSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewGeneratedSalary.setForeground(new java.awt.Color(255, 255, 204));
        viewGeneratedSalary.setText("View Generated Salaries");
        viewGeneratedSalary.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewGeneratedSalary.setMaximumSize(new java.awt.Dimension(150, 50));
        viewGeneratedSalary.setMinimumSize(new java.awt.Dimension(150, 50));
        viewGeneratedSalary.setPreferredSize(new java.awt.Dimension(150, 50));
        viewGeneratedSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewGeneratedSalaryActionPerformed(evt);
            }
        });

        AddEmployeeB.setBackground(new java.awt.Color(51, 51, 255));
        AddEmployeeB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddEmployeeB.setForeground(new java.awt.Color(255, 255, 204));
        AddEmployeeB.setText("Add Employees");
        AddEmployeeB.setActionCommand("View  Employees");
        AddEmployeeB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddEmployeeB.setMaximumSize(new java.awt.Dimension(150, 50));
        AddEmployeeB.setMinimumSize(new java.awt.Dimension(150, 50));
        AddEmployeeB.setPreferredSize(new java.awt.Dimension(150, 50));
        AddEmployeeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeBActionPerformed(evt);
            }
        });

        ViewEmployeeB.setBackground(new java.awt.Color(51, 51, 255));
        ViewEmployeeB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewEmployeeB.setForeground(new java.awt.Color(255, 255, 204));
        ViewEmployeeB.setText("View Employees");
        ViewEmployeeB.setActionCommand("View  Employees");
        ViewEmployeeB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewEmployeeB.setMaximumSize(new java.awt.Dimension(150, 50));
        ViewEmployeeB.setMinimumSize(new java.awt.Dimension(150, 50));
        ViewEmployeeB.setPreferredSize(new java.awt.Dimension(150, 50));
        ViewEmployeeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmployeeBActionPerformed(evt);
            }
        });

        UpdateEmployeeB.setBackground(new java.awt.Color(51, 51, 255));
        UpdateEmployeeB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateEmployeeB.setForeground(new java.awt.Color(255, 255, 204));
        UpdateEmployeeB.setText("Update Employee");
        UpdateEmployeeB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateEmployeeB.setMaximumSize(new java.awt.Dimension(150, 50));
        UpdateEmployeeB.setMinimumSize(new java.awt.Dimension(150, 50));
        UpdateEmployeeB.setPreferredSize(new java.awt.Dimension(150, 50));
        UpdateEmployeeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeBActionPerformed(evt);
            }
        });

        DeleteEmployeeB.setBackground(new java.awt.Color(51, 51, 255));
        DeleteEmployeeB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteEmployeeB.setForeground(new java.awt.Color(255, 255, 204));
        DeleteEmployeeB.setText("Delete Employee");
        DeleteEmployeeB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DeleteEmployeeB.setMaximumSize(new java.awt.Dimension(150, 50));
        DeleteEmployeeB.setMinimumSize(new java.awt.Dimension(150, 50));
        DeleteEmployeeB.setPreferredSize(new java.awt.Dimension(150, 50));
        DeleteEmployeeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEmployeeBActionPerformed(evt);
            }
        });

        viewGeneratedSalary1.setBackground(new java.awt.Color(51, 51, 255));
        viewGeneratedSalary1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewGeneratedSalary1.setForeground(new java.awt.Color(255, 255, 204));
        viewGeneratedSalary1.setText("View Summary");
        viewGeneratedSalary1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewGeneratedSalary1.setMaximumSize(new java.awt.Dimension(150, 50));
        viewGeneratedSalary1.setMinimumSize(new java.awt.Dimension(150, 50));
        viewGeneratedSalary1.setPreferredSize(new java.awt.Dimension(150, 50));
        viewGeneratedSalary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewGeneratedSalary1ActionPerformed(evt);
            }
        });

        viewAttB2.setBackground(new java.awt.Color(51, 51, 255));
        viewAttB2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewAttB2.setForeground(new java.awt.Color(255, 255, 204));
        viewAttB2.setText("Update Leave");
        viewAttB2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAttB2.setMaximumSize(new java.awt.Dimension(150, 50));
        viewAttB2.setMinimumSize(new java.awt.Dimension(150, 50));
        viewAttB2.setPreferredSize(new java.awt.Dimension(150, 50));
        viewAttB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAttB2ActionPerformed(evt);
            }
        });

        viewAttB3.setBackground(new java.awt.Color(51, 51, 255));
        viewAttB3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewAttB3.setForeground(new java.awt.Color(255, 255, 204));
        viewAttB3.setText("View Leaves");
        viewAttB3.setActionCommand("View Leaves");
        viewAttB3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAttB3.setMaximumSize(new java.awt.Dimension(150, 50));
        viewAttB3.setMinimumSize(new java.awt.Dimension(150, 50));
        viewAttB3.setPreferredSize(new java.awt.Dimension(150, 50));
        viewAttB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAttB3ActionPerformed(evt);
            }
        });

        viewAttB4.setBackground(new java.awt.Color(51, 51, 255));
        viewAttB4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewAttB4.setForeground(new java.awt.Color(255, 255, 204));
        viewAttB4.setText("Delete Leave");
        viewAttB4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAttB4.setMaximumSize(new java.awt.Dimension(150, 50));
        viewAttB4.setMinimumSize(new java.awt.Dimension(150, 50));
        viewAttB4.setPreferredSize(new java.awt.Dimension(150, 50));
        viewAttB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAttB4ActionPerformed(evt);
            }
        });

        viewAttB5.setBackground(new java.awt.Color(51, 51, 255));
        viewAttB5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewAttB5.setForeground(new java.awt.Color(255, 255, 204));
        viewAttB5.setText("Add Expense");
        viewAttB5.setActionCommand("Add Expense");
        viewAttB5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAttB5.setMaximumSize(new java.awt.Dimension(150, 50));
        viewAttB5.setMinimumSize(new java.awt.Dimension(150, 50));
        viewAttB5.setPreferredSize(new java.awt.Dimension(150, 50));
        viewAttB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAttB5ActionPerformed(evt);
            }
        });

        viewAttB6.setBackground(new java.awt.Color(51, 51, 255));
        viewAttB6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewAttB6.setForeground(new java.awt.Color(255, 255, 204));
        viewAttB6.setText("View Expense");
        viewAttB6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAttB6.setMaximumSize(new java.awt.Dimension(150, 50));
        viewAttB6.setMinimumSize(new java.awt.Dimension(150, 50));
        viewAttB6.setPreferredSize(new java.awt.Dimension(150, 50));
        viewAttB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAttB6ActionPerformed(evt);
            }
        });

        viewGeneratedSalary2.setBackground(new java.awt.Color(51, 51, 255));
        viewGeneratedSalary2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewGeneratedSalary2.setForeground(new java.awt.Color(255, 255, 204));
        viewGeneratedSalary2.setText("Update Expense");
        viewGeneratedSalary2.setActionCommand("Update Expense");
        viewGeneratedSalary2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewGeneratedSalary2.setMaximumSize(new java.awt.Dimension(150, 50));
        viewGeneratedSalary2.setMinimumSize(new java.awt.Dimension(150, 50));
        viewGeneratedSalary2.setPreferredSize(new java.awt.Dimension(150, 50));
        viewGeneratedSalary2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewGeneratedSalary2ActionPerformed(evt);
            }
        });

        viewAttB7.setBackground(new java.awt.Color(51, 51, 255));
        viewAttB7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewAttB7.setForeground(new java.awt.Color(255, 255, 204));
        viewAttB7.setText("Delete Expense");
        viewAttB7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAttB7.setMaximumSize(new java.awt.Dimension(150, 50));
        viewAttB7.setMinimumSize(new java.awt.Dimension(150, 50));
        viewAttB7.setPreferredSize(new java.awt.Dimension(150, 50));
        viewAttB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAttB7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(PanelSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DeleteEmployeeB, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(AddEmployeeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ViewEmployeeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateEmployeeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generateSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewAttB1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(delAttB, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(editAttB, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(viewGeneratedSalary1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewGeneratedSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewGeneratedSalary2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(viewAttB3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(addBonusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewAttB2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(viewAttB4, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(viewAttB5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(viewAttB6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(viewAttB7, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(assignBonusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewBonusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateBonusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteBonusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSide, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(99, 99, 99)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewAttB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewAttB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(AddEmployeeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(addBonusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeleteEmployeeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delAttB, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(assignBonusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewAttB2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewEmployeeB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBonusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editAttB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewAttB4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UpdateEmployeeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewGeneratedSalary1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(viewAttB5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(updateBonusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(deleteBonusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generateSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewGeneratedSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(viewAttB6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewGeneratedSalary2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewAttB7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(210, 210, 210))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteEmployeeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEmployeeBActionPerformed
        admin.deleteEmployee();
        dispose();
    }//GEN-LAST:event_DeleteEmployeeBActionPerformed

    private void UpdateEmployeeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeBActionPerformed
        admin.updateEmployee();
        dispose();
    }//GEN-LAST:event_UpdateEmployeeBActionPerformed

    private void ViewEmployeeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEmployeeBActionPerformed
        admin.viewEmployee();
        dispose();
    }//GEN-LAST:event_ViewEmployeeBActionPerformed

    private void AddEmployeeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeBActionPerformed
        admin.addEmployee();
        dispose();
    }//GEN-LAST:event_AddEmployeeBActionPerformed

    private void viewGeneratedSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGeneratedSalaryActionPerformed
        // TODO add your handling code here:
        admin.viewGeneratedSalaries();
        dispose();
    }//GEN-LAST:event_viewGeneratedSalaryActionPerformed

    private void generateSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateSalaryActionPerformed
        // TODO add your handling code here:
        admin.generateSalary();
        dispose();
    }//GEN-LAST:event_generateSalaryActionPerformed

    private void editAttBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAttBActionPerformed
        admin.updateAttendance();
        dispose();
    }//GEN-LAST:event_editAttBActionPerformed

    private void assignBonusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBonusButtonActionPerformed
        // TODO add your handling code here:
        admin.assignBonus();
        dispose();
    }//GEN-LAST:event_assignBonusButtonActionPerformed

    private void deleteBonusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBonusButtonActionPerformed
        // TODO add your handling code here:
       admin.deleteBonus();
        dispose();
    }//GEN-LAST:event_deleteBonusButtonActionPerformed

    private void updateBonusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBonusButtonActionPerformed
        // TODO add your handling code here:
        admin.updateBonus();
        dispose();
    }//GEN-LAST:event_updateBonusButtonActionPerformed

    private void viewBonusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBonusButtonActionPerformed
        // TODO add your handling code here:
        admin.viewBonus();
        dispose();
    }//GEN-LAST:event_viewBonusButtonActionPerformed

    private void addBonusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBonusButtonActionPerformed
        // TODO add your handling code here:
        admin.addBonus();
        dispose();
    }//GEN-LAST:event_addBonusButtonActionPerformed

    private void delAttBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAttBActionPerformed
        admin.deleteAttendance();
        dispose();
    }//GEN-LAST:event_delAttBActionPerformed

    private void viewAttB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAttB1ActionPerformed
        // TODO add your handling code here:
         admin.viewAttendance();
        this.dispose();
    }//GEN-LAST:event_viewAttB1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        admin.logout();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void viewGeneratedSalary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGeneratedSalary1ActionPerformed
         admin.viewSummary();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_viewGeneratedSalary1ActionPerformed

    private void viewAttB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAttB2ActionPerformed
        // TODO add your handling code here:
      admin.updateLeaves();
        dispose();
    }//GEN-LAST:event_viewAttB2ActionPerformed

    private void viewAttB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAttB3ActionPerformed
        // TODO add your handling code here:
        
          admin.viewLeaves();
        dispose();
    }//GEN-LAST:event_viewAttB3ActionPerformed

    private void viewAttB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAttB4ActionPerformed
        // TODO add your handling code here:
        admin.deleteLeave();
        dispose();
    }//GEN-LAST:event_viewAttB4ActionPerformed

    private void viewAttB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAttB5ActionPerformed
        // TODO add your handling code here:
        admin.addExpense();
        dispose();
    }//GEN-LAST:event_viewAttB5ActionPerformed

    private void viewAttB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAttB6ActionPerformed
        // TODO add your handling code here:
        admin.viewExpense();
        dispose();
    }//GEN-LAST:event_viewAttB6ActionPerformed

    private void viewGeneratedSalary2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGeneratedSalary2ActionPerformed
        // TODO add your handling code here:
        admin.updateExpense();
        dispose();
    }//GEN-LAST:event_viewGeneratedSalary2ActionPerformed

    private void viewAttB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAttB7ActionPerformed
        // TODO add your handling code here:
        admin.deleteExpense();
        dispose();
    }//GEN-LAST:event_viewAttB7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployeeB;
    private javax.swing.JButton DeleteEmployeeB;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelSide;
    private javax.swing.JButton UpdateEmployeeB;
    private javax.swing.JButton ViewEmployeeB;
    private javax.swing.JButton addBonusButton;
    private javax.swing.JButton assignBonusButton;
    private javax.swing.JButton delAttB;
    private javax.swing.JButton deleteBonusButton;
    private javax.swing.JButton editAttB;
    private javax.swing.JButton generateSalary;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton updateBonusButton;
    private javax.swing.JButton viewAttB1;
    private javax.swing.JButton viewAttB2;
    private javax.swing.JButton viewAttB3;
    private javax.swing.JButton viewAttB4;
    private javax.swing.JButton viewAttB5;
    private javax.swing.JButton viewAttB6;
    private javax.swing.JButton viewAttB7;
    private javax.swing.JButton viewBonusButton;
    private javax.swing.JButton viewGeneratedSalary;
    private javax.swing.JButton viewGeneratedSalary1;
    private javax.swing.JButton viewGeneratedSalary2;
    // End of variables declaration//GEN-END:variables
}
